### ISSUE TITLE
 require() of ES Module  not supported.

### ISSUE THREAD

**Issue by raaaas** [bobthered/vite-plugin-socket.io#2]
following exactly as tut , 

> my pkg.js (
> {
>   "name": "TronBe",
>   "version": "1.0.0",
>   "scripts": {
>     "dev": "vite --host",
>     "build": "vite build",
>     "serve": "vite preview"
>   },
>   "dependencies": {
>     "@vueuse/core": "^8.2.5",
>     "autoprefixer": "^10.4.7",
>     "axios": "^0.27.2",
>     "dompurify": "^2.3.8",
>     "dotenv": "^16.0.1",
>     "encrypt-storage": "^2.2.10",
>     "ethers": "^5.6.5",
>     "nanoid": "^3.1.3",
>     "pinia": "^2.0.14",
>     "postcss": "^8.4.13",
>     "postcss-cli": "^8.1.0",
>     "postcss-loader": "^3.0.0",
>     "postcss-reporter": "^6.0.1",
>     "socket.io-client": "^4.5.0",
>     "timeago.js": "^4.0.2",
>     "tronweb": "^4.1.0",
>     "vite-plugin-socket-io": "^1.0.2",
>     "vue": "^3.2.33",
>     "vue-router": "^4.0.15",
>     "web3": "^1.7.3"
>   },
>   "devDependencies": {
>     "@headlessui/vue": "^1.6.1",
>     "@heroicons/vue": "^1.0.6",
>     "@tailwindcss/aspect-ratio": "^0.4.0",
>     "@tailwindcss/forms": "^0.5.1",
>     "@tailwindcss/line-clamp": "^0.4.0",
>     "@tailwindcss/postcss7-compat": "^2.2.17",
>     "@tailwindcss/typography": "^0.5.2",
>     "@types/tailwindcss": "^3.0.10",
>     "@vitejs/plugin-vue": "^2.3.2",
>     "autoprefixer": "^10.4.7",
>     "node-sass": "^7.0.1",
>     "prettier": "^2.5.1",
>     "prettier-plugin-tailwindcss": "^0.1.10",
>     "sass": "^1.51.0",
>     "tailwindcss": "^3.0.24",
>     "vite": "^2.9.8"
>   }
> }

had very hard time to yarn add 
> npm i -D vite-plugin-socket.io
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/vite-plugin-socket.io - Not found
> 
> 
that beside it wond work as told in readme .

```

yarn run v1.22.15
warning package.json: No license field
$ vite --host
failed to load config from I:\work\game\vvt-app\vite.config.js
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module I:\work\game\vvt-app\node_modules\vite-plugin-socket-io\index.js from I:\work\game\vvt-app\vite.config.js not supported.
Instead change the require of index.js in I:\work\game\vvt-app\vite.config.js to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (I:\work\game\vvt-app\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:61927:13)
    at Object.<anonymous> (I:\work\game\vvt-app\vite.config.js:31:44)
    at Object.require.extensions.<computed> [as .js] (I:\work\game\vvt-app\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:61924:20)
    at loadConfigFromBundledFile (I:\work\game\vvt-app\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:61932:17)
    at loadConfigFromFile (I:\work\game\vvt-app\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:61851:32)
    at async resolveConfig (I:\work\game\vvt-app\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:61376:28)
    at async createServer (I:\work\game\vvt-app\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:59783:20)
    at async CAC.<anonymous> (I:\work\game\vvt-app\node_modules\vite\dist\node\cli.js:688:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Miadatsiory** [comment]
Hi, can have some solution for this issue guys. thanks.

**Comment by raaaas** [comment]
> Hi, can have some solution for this issue guys. thanks.

i fixed same problem , not this one, by updating my node and/or downgrade my packages,

**Comment by Miadatsiory** [comment]
thank you, i fix it by changing  vite-plugin-socket.io by vite-plugin-socket-io
